---
- name: Deploy redis container
  hosts: all
  tasks:
    - name: update the system
      yum:
       name: "*"
       state: latest
    - name: Start service docker, if not started
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
    - name: create docker container
      docker_container:
        name: redis
        image: redis
        state: started
      become: yes
