
---
- name: Deploy redis container
  hosts: localhost
  vars:
    redis_enablerepo: epel
    redis_port: 6379
    redis_bind: 127.0.0.1
    - name: docker
  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - davidwittman.redis
  tasks:
    - name: update the system
      yum:
       name: "*"
       state: latest
    - name: install epel
      yum:
        name: epel-release
        state: present
      become: yes

    - name: install docker-compose
      yum:
        name: docker-compose
        state: present
      become: yes

    - name: Start service docker, if not started
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: install pip
      yum:
        name: python-pip
        state: present
      become: yes

    - name: create docker container
      docker_container:
        name: redis
        image: redis
        state: started
      become: yes

